CAMPAIGN_START = "campaign_start"
CAMPAIGN_END = "campaign_end"
SETUP = "setup"
PRE_FLIGHT_SNAPSHOT = "pre_flight_snapshot"
UPLOAD_PHASE = "upload_phase"
PRELUDE_TURN_SENT = "prelude_turn_sent"
PRELUDE_TURN_RECV = "prelude_turn_recv"
ATTACK_TURN_SENT = "attack_turn_sent"
ATTACK_TURN_RECV = "attack_turn_recv"
POST_RUN_SNAPSHOT = "post_run_snapshot"
EVAL_RESULT = "eval_result"
REFLECT_RESULT = "reflect_result"
# Budget subsystem events
BUDGET_CHECK = "budget_check"
BUDGET_EXHAUSTED = "budget_exhausted"
BUDGET_CYCLE_SUMMARY = "budget_cycle_summary"
TOOL_BUDGET_WARNING = "tool_budget_warning"
TOOL_BUDGET_EXHAUSTED = "tool_budget_exhausted"
# Think + streaming events
THINK_STEP = "think_step"
SUBAGENT_START = "subagent_start"
SUBAGENT_END = "subagent_end"
VALIDATION_REPORT = "validation_report"
# MUZZLE loop lifecycle events
EXPLORATION_START = "exploration_start"
EXPLORATION_END = "exploration_end"
GRAFTER_DISCOVER = "grafter_discover"
GRAFTER_RANK = "grafter_rank"
OBJECTIVE_ELICIT = "objective_elicit"
OBJECTIVE_DISTILL = "objective_distill"
CYCLE_START = "cycle_start"
CYCLE_END = "cycle_end"
